kind: PersistentVolume
apiVersion: v1
metadata: 
  name: PersistentVolume
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  acessModes: 
    -ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage\
  hostPath:
    path: /mnt/data