kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata: 
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-con
        image: aman9048/notes-app:latest
        ports:
        - containerPort: 8000
